"""add_userprofile

Revision ID: 3cec693a8eba
Revises: 187d6bb64350
Create Date: 2026-04-12 03:02:52.186787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3cec693a8eba'
down_revision: Union[str, Sequence[str], None] = '187d6bb64350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_of_birth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userprofile_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_userprofile_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userprofile_username'))
        batch_op.drop_index(batch_op.f('ix_userprofile_email'))

    op.drop_table('userprofile')
    # ### end Alembic commands ###
