"""empty message

Revision ID: ddf6f2aa327e
Revises: 0d5ab6789ea6
Create Date: 2026-04-24 15:55:12.601980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ddf6f2aa327e'
down_revision: Union[str, Sequence[str], None] = '0d5ab6789ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagerecord', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exif_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagerecord', schema=None) as batch_op:
        batch_op.drop_column('exif_info')

    # ### end Alembic commands ###
